version: '3.8'

services:
  # 1. Data Base
  db:
    image: postgres:15-alpine
    container_name: sticky-notes_db_prod
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  # 2. Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: sticky-notes_backend_prod
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/notes_db
    depends_on:
      - db

  # 3. Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: sticky-notes_frontend_prod
    restart: always

  # 4. Proxy (Nginx Gateway)
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: sticky-notes_proxy_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data_prod: